import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"; 
import "./app.css"; 
import Navbar from './components/navbar'; // Import Navbar
import Footer from './components/Footer'; // Import Footer

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-full flex flex-col`}>
        <Navbar /> {/* Add Navbar here */}
        <main className="flex-1 mt-16 w-full flex flex-col justify-center items-center">
          {children}
        </main>
        <Footer /> {/* Add Footer here */}
      </body>
    </html>
  );
}
