import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"; 
import "./app.css"; 
import Navbar from './components/navbar'; // Import Navbar

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-full`}>
        <Navbar /> {/* Add Navbar here */}
        <main className="flex-1 flex flex-col justify-center items-center mt-16">
          {children}
        </main>
      </body>
    </html>
  );
}

